version: '3.1'

services:

  api:
    image: nanoninja/php-fpm:8.1
    depends_on:
      - postgres
      - mailhog
      # - redis
    ports:
      - 8000:8000
    volumes:
      - ./:/var/www/html
    command: php -S="0.0.0.0:8000" -t="/var/www/html/public"
    #command: php artisan serve

  # redis:
  #   image: redis:6.2-alpine
  #   restart: always
  #   ports:
  #     - '6379:6379'
  #   command: ["redis-server", "--appendonly", "yes", "--requirepass", "password"]

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      - TZ=America/Argentina/Buenos_Aires
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - pgdata:/var/lib/postgresql/data

  # mysql:
  #   image: mysql:latest
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   ports:
  #     - '3306:3306'
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password
  #   volumes:
  #     - mydata:/var/lib/mysql

  endpoint_adminer:
    image: adminer:latest
    restart: always
    depends_on:
      - postgres
      # - mysql
    ports:
      - 9000:8080

  mailhog:
      image: 'mailhog/mailhog:latest'
      ports:
        - '1025:1025'
        - '8025:8025'
volumes:
  pgdata:
    driver: local
  mydata:
    driver: local
