version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - postgres
    environment:
      - APP_NAME=Aguas Nico
      - APP_ENV=local
      - APP_KEY=base64:oRYP+dGQvFMAMkAX/Fu5Yu7pF6Hgx1Ycu02XYALg8qc=
      - APP_DEBUG=true
      - APP_URL=http://localhost/
      - APP_LOCALE=es
      - LOG_CHANNEL=stack
      - LOG_DEPRECATIONS_CHANNEL=null
      - LOG_LEVEL=debug
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=aguasnico_app
      - DB_USERNAME=postgres
      - DB_PASSWORD=password

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: aguasnico_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"
